[general]
GEMINI_API_KEY = "AIzaSyBloD2NOzyiiEh8voaskUYO75CKEJz4hHo"
ANTHROPIC_API_KEY = "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"
GEMINI_MODEL = "gemini-2.0-flash"


[mysql]
host = "localhost"
user = "root"
password = "fais914!"  # Change to your actual password
database = "streamlit_app"
port = 3306